trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- task: DownloadSecureFile@1
  name: myChefPem
  displayName: 'Download - Chef Starter kit pem file'
  inputs:
    secureFile: 'srikarpasham.pem'
