trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- script: |
    echo "First pipeline script"
    echo "Another line of code"

- script: |
    export CHEF_LICENSE=accept
    wget https://packages.chef.io/files/stable/chef-workstation/0.17.5/ubuntu/16.04/chef-workstation_0.17.5-1_amd64.deb
    sudo dpkg -i chef-workstation_0.17.5-1_amd64.deb
    chef -v
  displayName: 'Installing Chef Workstation'

- script: |
    export CHEF_LICENSE=accept
    chef gem install kitchen-docker
  displayName: 'Installing kitchen-docker gem'

- script: |
   /opt/chef-workstation/bin/chef exec cookstyle . --except Layout/EndOfLine 
  displayName: 'Run Cookstyle'

- script: | 
    kitchen destroy
  displayName: 'Destroy any existing kitchen'

- script: |
    kitchen create
  displayName: 'Create a new kitchen'

- script: | 
    kitchen converge
  displayName: 'Converge the new kitchen'

- script: |
    kitchen verify
  displayName: 'verify your tests against the new kitchen'

- script: |
    kitchen destroy
  displayName: 'Destroy the kitchen'

- task: PublishBuildArtifacts@1
  displayName: 'Publish cookbook to Release pipeline'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'

