trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- task: DownloadSecureFile@1
  name: myInstanceKey
  displayName: 'Download - VM Instance SSH Key'
  inputs:
    secureFile: 'vm-instance-key.pem'

- script: |
    echo "Writing $(myInstanceKey.secureFilePath) to the .chef directory"
    sudo ln -s $(myInstanceKey.secureFilePath) .chef/vmInstanceKey
    ls -la .chef/
  displayName: 'Writing VM Instance SSH Key'
