trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- task: DownloadSecureFile@1
  name: myChefPem
  displayName: 'Download - Chef Starter kit pem file'
  inputs:
    secureFile: 'srikarpasham.pem'

- script: |
    echo "Writing $(myChefPem.secureFilePath) to the .chef directory"
    mkdir .chef
    sudo ln -s $(myChefPem.secureFilePath) .chef/chefPem
    ls -la .chef/
  displayName: 'Writing Chef pem file'
